spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: create